using static MusicTheory.API.Services.Transcription.BasicPitchGrid;
using static MusicTheory.API.Services.Transcription.BasicPitchMath;
using static MusicTheory.API.Services.Transcription.BasicPitchOnsets;

namespace MusicTheory.API.Services.Transcription;

/// <summary>
/// Basic Pitch's posteriorgram-to-note decoder, ported from the npm package's
/// <c>toMidi.ts</c> so it can run server-side.
///
/// <para>
/// This is the piece the two-tier design moves across the wire. Decoding stays
/// in the browser and derivation stays in the browser; what a seat buys is
/// inference and <em>this</em>, because this is where the ten seconds are. The
/// client keeps calling the same <c>NoteDetector</c> interface and cannot tell
/// which runtime produced the notes.
/// </para>
///
/// <para><b>It is a transliteration, not a rewrite, and that is on purpose.</b>
/// Every deviation from <c>toMidi.ts</c> is a chance for the two tiers to
/// disagree about a note, so the structure, the loop bounds, the order of
/// operations and the tie-breaking are all preserved even where they are odd —
/// and several are odd. The three places this file knowingly departs are each
/// argued at their site:
/// </para>
/// <list type="bullet">
///   <item><description>The melodia loop finds its maximum through
///   <see cref="BasicPitchMath.RowMaxIndex"/> rather than by rescanning: two
///   full passes over the matrix per iteration become one pass over a cached
///   column of row maxima. Provably the same answer, including ties, and worth
///   12x on a stem-length input. <see cref="BasicPitchMath.MaxCell"/> keeps the
///   naive scan as the reference the cache is tested against.</description></item>
///   <item><description>The melodia pass computes a note's amplitude after the
///   length check rather than before, because the discarded value it computes
///   first would index outside the array in a language that checks.</description></item>
///   <item><description><c>frameThresh</c> is nullable here, which reaches the
///   mean-plus-standard-deviation branch that is dead in TypeScript. The
///   default is unchanged.</description></item>
/// </list>
///
/// <para><b>Bit-equality with the browser is not claimed and is not the test.</b>
/// TF.js is not bit-reproducible between runs near the 0.3 frame threshold —
/// measured, when a fixture's 86 same-attack pairs came back as 89 from a live
/// session — so the two tiers were never going to agree on the last bit of a
/// borderline detection whatever this file did. The acceptance criterion is the
/// derived <c>ScoreDoc</c>. What this file <em>does</em> guarantee is that given
/// identical posteriorgrams it returns identical notes, which is the half of the
/// problem a port can be held to; <c>BasicPitchNotesDifferentialTests</c> pins
/// exactly that against vectors generated by running the TypeScript.
/// </para>
///
/// <para>
/// One arithmetic note, since it is invisible and load-bearing: the
/// posteriorgrams arrive from ONNX as <c>float</c> and are widened to
/// <c>double</c> before anything touches them, because JavaScript has no other
/// kind of number. Summing float32 activations in float32 would drift from the
/// browser on long notes for no reason at all. Widening is exact; the sums then
/// match.
/// </para>
///
/// <para>
/// <b>Where the rest of <c>toMidi.ts</c> went.</b> One upstream module became
/// five files here, to stay under this project's file-length rule, split along
/// the section comments the original already carries so that the
/// read-them-side-by-side property survives. Nothing was reworded in the move:
/// the bodies are textually what they were, reaching their helpers through
/// <c>using static</c> rather than through a rename.
/// </para>
/// <list type="table">
///   <item><term><see cref="BasicPitchGrid"/></term><description>the module
///   constants and <c>PORTED LIBROSA FUNCTIONS</c></description></item>
///   <item><term><see cref="BasicPitchMath"/></term><description><c>PORTED NUMPY
///   FUNCTIONS</c>, the gaussian window, and the row-max index</description></item>
///   <item><term><see cref="BasicPitchOnsets"/></term><description><c>constrainFrequency</c>
///   and <c>getInferredOnsets</c></description></item>
///   <item><term>this file</term><description><c>outputToNotesPoly</c>, the
///   melodia pass, and <c>noteFramesToTime</c></description></item>
///   <item><term><see cref="BasicPitchBends"/></term><description><c>addPitchBendsToNoteEvents</c></description></item>
/// </list>
/// </summary>
public static class BasicPitchNotes
{
    /// <summary>
    /// Decodes frame and onset posteriorgrams into polyphonic note events.
    /// </summary>
    /// <param name="frames">Frame activations, <c>[time][pitch]</c>. Mutated by
    /// <paramref name="maxFreq"/>/<paramref name="minFreq"/>, as in the original.</param>
    /// <param name="onsets">Onset activations, <c>[time][pitch]</c>. Also mutated.</param>
    /// <param name="onsetThresh">Minimum onset activation to count as an attack.</param>
    /// <param name="frameThresh">Minimum frame activation to keep a note sounding.
    /// Null infers it as the mean plus one standard deviation of
    /// <paramref name="frames"/> — a branch the TypeScript declares and can never
    /// reach, because its parameter is typed non-null with a default of 0.3.</param>
    /// <param name="minNoteLen">Shortest allowed note, in frames.</param>
    /// <param name="inferOnsets">Add onsets inferred from rises in frame energy.</param>
    /// <param name="maxFreq">Upper frequency bound in Hz, or null for none.</param>
    /// <param name="minFreq">Lower frequency bound in Hz, or null for none.</param>
    /// <param name="melodiaTrick">Sweep up the energy left over after the onset
    /// pass, which is where notes without a detected attack come from.</param>
    /// <param name="energyTolerance">Frames a note may spend below
    /// <paramref name="frameThresh"/> before it is considered over.</param>
    public static List<NoteEvent> OutputToNotesPoly(
        double[][] frames,
        double[][] onsets,
        double onsetThresh = 0.5,
        double? frameThresh = 0.3,
        int minNoteLen = 5,
        bool inferOnsets = true,
        double? maxFreq = null,
        double? minFreq = null,
        bool melodiaTrick = true,
        int energyTolerance = 11)
    {
        ArgumentNullException.ThrowIfNull(frames);
        ArgumentNullException.ThrowIfNull(onsets);

        double inferredFrameThresh;
        if (frameThresh is null)
        {
            var (mean, std) = MeanStdDev(frames);
            inferredFrameThresh = mean + std;
        }
        else
        {
            inferredFrameThresh = frameThresh.Value;
        }

        var nFrames = frames.Length;
        if (nFrames == 0)
        {
            return [];
        }

        ConstrainFrequency(onsets, frames, maxFreq, minFreq);

        var inferredOnsets = inferOnsets ? GetInferredOnsets(onsets, frames) : onsets;

        // A hacky form of zeros-like, then the relative maxima scattered back
        // into it: only a peak in time can start a note, so a plateau above the
        // threshold contributes one attack rather than a dozen.
        var peakThresholdMatrix = inferredOnsets.Select(row => new double[row.Length]).ToArray();
        foreach (var (row, col) in ArgRelMax(inferredOnsets))
        {
            peakThresholdMatrix[row][col] = inferredOnsets[row][col];
        }

        var (noteStarts, freqIdxs) = WhereGreaterThanAxis1(peakThresholdMatrix, onsetThresh);

        // Reversed, so the search runs backwards through the file. This is not
        // cosmetic: each note it accepts zeroes its own band out of
        // remainingEnergy, so the order decides which of two overlapping attacks
        // gets the energy between them.
        noteStarts.Reverse();
        freqIdxs.Reverse();

        var remainingEnergy = frames.Select(row => (double[])row.Clone()).ToArray();

        var noteEvents = new List<NoteEvent>();

        for (var idx = 0; idx < noteStarts.Count; idx++)
        {
            var noteStartIdx = noteStarts[idx];
            var freqIdx = freqIdxs[idx];

            // Too close to the end of the audio to say anything about.
            if (noteStartIdx >= nFrames - 1)
            {
                continue;
            }

            // Walk forward to where this band's energy stays below threshold for
            // energyTolerance frames.
            var i = noteStartIdx + 1;
            var k = 0;
            while (i < nFrames - 1 && k < energyTolerance)
            {
                k = remainingEnergy[i][freqIdx] < inferredFrameThresh ? k + 1 : 0;
                i += 1;
            }

            i -= k; // back to the last frame above threshold

            if (i - noteStartIdx <= minNoteLen)
            {
                // Note skipped, and its energy deliberately left in place: the
                // original does not clear it, so the melodia pass can still find
                // it.
                continue;
            }

            for (var j = noteStartIdx; j < i; j++)
            {
                ClearBand(remainingEnergy, j, freqIdx);
            }

            noteEvents.Add(new NoteEvent
            {
                StartFrame = noteStartIdx,
                DurationFrames = i - noteStartIdx,
                PitchMidi = freqIdx + MidiOffset,
                Amplitude = MeanOverBand(frames, noteStartIdx, i, freqIdx)
            });
        }

        if (melodiaTrick)
        {
            RunMelodiaTrick(
                frames,
                remainingEnergy,
                noteEvents,
                nFrames,
                inferredFrameThresh,
                minNoteLen,
                energyTolerance);
        }

        return noteEvents;
    }

    /// <summary>
    /// Sweeps up frame energy the onset pass did not claim, growing a note
    /// outward from each remaining peak until it dies in both directions.
    /// </summary>
    /// <remarks>
    /// This is where the running time lives. Every iteration finds the largest
    /// remaining cell and erases a band around the note it grows, so the loop is
    /// bounded by the energy it removes rather than by any count known in advance
    /// — which is exactly why the original's two full scans per iteration cost
    /// what they cost. See <see cref="MaxCell"/>.
    /// </remarks>
    private static void RunMelodiaTrick(
        double[][] frames,
        double[][] remainingEnergy,
        List<NoteEvent> noteEvents,
        int nFrames,
        double inferredFrameThresh,
        int minNoteLen,
        int energyTolerance)
    {
        var index = new RowMaxIndex(remainingEnergy);

        while (true)
        {
            var (iMid, freqIdx, max) = index.MaxCell();
            if (!(max > inferredFrameThresh))
            {
                break;
            }

            remainingEnergy[iMid][freqIdx] = 0;
            index.Invalidate(iMid);

            // Forward pass.
            var i = iMid + 1;
            var k = 0;
            while (i < nFrames - 1 && k < energyTolerance)
            {
                k = remainingEnergy[i][freqIdx] < inferredFrameThresh ? k + 1 : 0;
                ClearBand(remainingEnergy, i, freqIdx);
                index.Invalidate(i);
                i += 1;
            }

            var iEnd = i - 1 - k;

            // Backwards pass.
            i = iMid - 1;
            k = 0;
            while (i > 0 && k < energyTolerance)
            {
                k = remainingEnergy[i][freqIdx] < inferredFrameThresh ? k + 1 : 0;
                ClearBand(remainingEnergy, i, freqIdx);
                index.Invalidate(i);
                i -= 1;
            }

            var iStart = i + 1 + k;

            if (iStart < 0)
            {
                throw new InvalidOperationException($"iStart is not positive! value: {iStart}");
            }

            if (iEnd >= nFrames)
            {
                throw new InvalidOperationException(
                    $"iEnd is past end of times. (iEnd, times.length): ({iEnd}, {nFrames})");
            }

            // The original computes the amplitude here and throws it away when
            // the note is too short. Deferred past the check instead, because a
            // rejected note can have iStart greater than iEnd, and the slice that
            // silently yields nothing in JavaScript is an exception in C#. Every
            // note that survives the check spans a valid range, so no kept note
            // changes.
            if (iEnd - iStart <= minNoteLen)
            {
                continue;
            }

            noteEvents.Add(new NoteEvent
            {
                StartFrame = iStart,
                DurationFrames = iEnd - iStart,
                PitchMidi = freqIdx + MidiOffset,
                Amplitude = MeanOverBand(frames, iStart, iEnd, freqIdx)
            });
        }
    }

    /// <summary>Zeroes a pitch and its two neighbours at one frame.</summary>
    private static void ClearBand(double[][] remainingEnergy, int frame, int freqIdx)
    {
        remainingEnergy[frame][freqIdx] = 0;
        if (freqIdx < MaxFreqIdx)
        {
            remainingEnergy[frame][freqIdx + 1] = 0;
        }

        if (freqIdx > 0)
        {
            remainingEnergy[frame][freqIdx - 1] = 0;
        }
    }

    /// <summary>
    /// Mean frame activation over <c>[start, end)</c> at one pitch — the number
    /// that ends up in <see cref="NoteEvent.Amplitude"/>.
    /// </summary>
    /// <remarks>
    /// Accumulated left to right in double precision, which is what makes it
    /// match the browser's <c>reduce</c> bit for bit rather than merely closely.
    /// </remarks>
    private static double MeanOverBand(double[][] frames, int start, int end, int freqIdx)
    {
        var sum = 0.0;
        for (var r = start; r < end; r++)
        {
            sum += frames[r][freqIdx];
        }

        return sum / (end - start);
    }

    /// <summary>Resolves each note's frames to seconds.</summary>
    public static List<NoteEventTime> NoteFramesToTime(IReadOnlyList<NoteEvent> notes)
    {
        ArgumentNullException.ThrowIfNull(notes);

        var result = new List<NoteEventTime>(notes.Count);
        foreach (var note in notes)
        {
            var start = ModelFrameToTime(note.StartFrame);
            result.Add(new NoteEventTime
            {
                PitchMidi = note.PitchMidi,
                Amplitude = note.Amplitude,
                PitchBends = note.PitchBends,
                StartTimeSeconds = start,

                // Not durationFrames converted directly: the window-overlap
                // correction is a step function of the frame index, so a note
                // that straddles a window boundary is shorter in seconds than its
                // frame count suggests. Converting both ends and subtracting is
                // what picks that up.
                DurationSeconds = ModelFrameToTime(note.StartFrame + note.DurationFrames) - start
            });
        }

        return result;
    }
}
